//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCalculator.CalculatorReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorReference.Calculator_ASMXSoap")]
    public interface Calculator_ASMXSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        double Add(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtrct", ReplyAction="*")]
        double Subtrct(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        double Multiply(double f1, double f2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divide", ReplyAction="*")]
        double Divide(double f1, double f2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Calculator_ASMXSoapChannel : SimpleCalculator.CalculatorReference.Calculator_ASMXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Calculator_ASMXSoapClient : System.ServiceModel.ClientBase<SimpleCalculator.CalculatorReference.Calculator_ASMXSoap>, SimpleCalculator.CalculatorReference.Calculator_ASMXSoap {
        
        public Calculator_ASMXSoapClient() {
        }
        
        public Calculator_ASMXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Calculator_ASMXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Calculator_ASMXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Calculator_ASMXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double f1, double f2) {
            return base.Channel.Add(f1, f2);
        }
        
        public double Subtrct(double f1, double f2) {
            return base.Channel.Subtrct(f1, f2);
        }
        
        public double Multiply(double f1, double f2) {
            return base.Channel.Multiply(f1, f2);
        }
        
        public double Divide(double f1, double f2) {
            return base.Channel.Divide(f1, f2);
        }
    }
}
